### ISSUE TITLE
您好，尊敬的师兄，这是一封求教信

### ISSUE THREAD

**Issue by heaoli** [jch12138/two-stage-structure-damage-detection#1]
师兄，您好！非常有幸阅读到您的A Two-Stage Structural Damage Detection Method Based on
1D-CNN and SVM这篇文章，因为我看您说能提供这个文章的代码，但是我在github上没有找到，请问您能发一下代码让我学习一下吗，如果可以的话非常感谢您，祝您科研顺利！

**Comment by jch12138** [comment]
实在不好意思，之前一直没有时间整理代码，今天整理的时候发现之前服务器出故障，有部分代码文件（比如第二阶段训练svm的代码）不见了，我把能找到的都上传了。然后数据因为是实验室自己采集的，所以不能公开，代码当时刚入门也写的比较混乱。

**Comment by heaoli** [comment]
太感谢师兄了，谢谢
